# Generated by Django 5.2.1 on 2026-01-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('dtm_id', models.IntegerField(default=0, unique=True)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('ip_port', models.PositiveIntegerField(verbose_name=0)),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
                'db_table': 'region',
            },
        ),
    ]
