# Generated by Django 5.2.1 on 2026-01-24 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Minimum chegara',
                'verbose_name_plural': 'Minimum chegaralar',
                'db_table': 'minscore',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('mode', models.PositiveSmallIntegerField(default=0)),
                ('is_check_face_staff', models.BooleanField(default=False)),
                ('is_check_face_candidate', models.BooleanField(default=False)),
                ('is_screen_record', models.BooleanField(default=False)),
                ('is_face_identification', models.BooleanField(default=False)),
                ('timer_face_id', models.PositiveSmallIntegerField(default=10)),
                ('is_detect_cheating', models.BooleanField(default=False)),
                ('is_detect_monitor', models.BooleanField(default=False)),
                ('is_detect_camera', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sozlama',
                'verbose_name_plural': 'Sozlamalar',
                'db_table': 'settings',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IPCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('mac_address', models.CharField(max_length=255, unique=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.region')),
            ],
            options={
                'verbose_name': 'IP Camera',
                'verbose_name_plural': 'IP Cameras',
                'db_table': 'ipcamera',
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('mac_address', models.CharField(max_length=255, unique=True)),
                ('info_pc', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.ipcamera')),
            ],
            options={
                'verbose_name': 'Kompyuter',
                'verbose_name_plural': 'Kompyuterlar',
                'db_table': 'computer',
                'abstract': False,
            },
        ),
    ]
