# Generated by Django 5.2.1 on 2026-01-24 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningNotif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imei', models.CharField(blank=True, max_length=14, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings_exam', to='exams.test')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings_pc', to='settings.computer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
